#!/usr/bin/env bash

#wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_dark.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_light.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_light_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_dark_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_dark.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_dark_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_light_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_light.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/tenda_red.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/stornur_v1.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/olio_v1.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/tomatrap_v1.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/urbane.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/w0rm_blue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/evolved_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_asus_v2.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_belkin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/w0rm_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/w0rm_orange.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/openlinksys2.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3_wide.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3_wide_nogirl.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3_nogirl.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_violet.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_red.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_green.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_zyan.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_cyan.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_bronze.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_cisco.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_asus.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v2_hdtv.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v2_small.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v2.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/cisco.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/linksys.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/enlightened.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/redmodern.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/absolon_skin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/bluedream.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/tijaune.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/hal.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/dwoz.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/brownlight.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/absolon_buffalo.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/usbred.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/usbblue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rtn66u.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_pumpkin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_olive.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_cyan.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_brown.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_bluegreen_darker.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_blue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_black.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_asus.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_buffalo.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_dlink.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_linksys.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_netgear.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/linksysred.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/asusred.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/asus.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rs232.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_aqua.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_azure.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_banana.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_black.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_blue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_cherry.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_chocolate.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_earth.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_eggplant.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_emerald.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_gold.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_green.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_gunmetal.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_hotpink.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_lavender.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_lightpurple.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_lime.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_magenta.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_melon.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_mint.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_mustard.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_navy.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_olive.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_orange.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_peach.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_petrol.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_pink.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_pumpkin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_purple.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_red.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_rosybrown.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_salmon.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_sand.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_smoke.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_strawberry.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_turquise.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_wheat.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_white.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_yellow.zip
