#!/usr/bin/env bash

wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_dark.zip -O ./zip/advanced_v2_dark.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_light.zip -O ./zip/advanced_v2_light.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_light_noi.zip -O ./zip/advanced_v2_light_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v2_dark_noi.zip -O ./zip/advanced_v2_dark_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_dark.zip -O ./zip/advanced_v1_dark.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_dark_noi.zip -O ./zip/advanced_v1_dark_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_light_noi.zip -O ./zip/advanced_v1_light_noi.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/advanced_v1_light.zip -O ./zip/advanced_v1_light.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/tenda_red.zip -O ./zip/tenda_red.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/stornur_v1.zip -O ./zip/stornur_v1.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/olio_v1.zip -O ./zip/olio_v1.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/tomatrap_v1.zip -O ./zip/tomatrap_v1.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/urbane.zip -O ./zip/urbane.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/w0rm_blue.zip -O ./zip/w0rm_blue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/evolved_grey.zip -O ./zip/evolved_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_asus_v2.zip -O ./zip/darkknight_asus_v2.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_belkin.zip -O ./zip/darkknight_belkin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/w0rm_grey.zip -O ./zip/w0rm_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/w0rm_orange.zip -O ./zip/w0rm_orange.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/openlinksys2.zip -O ./zip/openlinksys2.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3_wide.zip -O ./zip/ilhm_v3_wide.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3_wide_nogirl.zip -O ./zip/ilhm_v3_wide_nogirl.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3.zip -O ./zip/ilhm_v3.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v3_nogirl.zip -O ./zip/ilhm_v3_nogirl.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_violet.zip -O ./zip/rdh_violet.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_red.zip -O ./zip/rdh_red.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_grey.zip -O ./zip/rdh_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_green.zip -O ./zip/rdh_green.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_zyan.zip -O ./zip/rdh_zyan.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_cyan.zip -O ./zip/rdh_cyan.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh_bronze.zip -O ./zip/rdh_bronze.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rdh.zip -O ./zip/rdh.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_cisco.zip -O ./zip/darkknight_cisco.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/darkknight_asus.zip -O ./zip/darkknight_asus.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v2_hdtv.zip -O ./zip/ilhm_v2_hdtv.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v2_small.zip -O ./zip/ilhm_v2_small.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm_v2.zip -O ./zip/ilhm_v2.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/cisco.zip -O ./zip/cisco.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/linksys.zip -O ./zip/linksys.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/enlightened.zip -O ./zip/enlightened.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/redmodern.zip -O ./zip/redmodern.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/ilhm.zip -O ./zip/ilhm.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/absolon_skin.zip -O ./zip/absolon_skin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/bluedream.zip -O ./zip/bluedream.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/tijaune.zip -O ./zip/tijaune.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/hal.zip -O ./zip/hal.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/dwoz.zip -O ./zip/dwoz.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/brownlight.zip -O ./zip/brownlight.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/absolon_buffalo.zip -O ./zip/absolon_buffalo.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/usbred.zip -O ./zip/usbred.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/usbblue.zip -O ./zip/usbblue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rtn66u.zip -O ./zip/rtn66u.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_pumpkin.zip -O ./zip/original_pumpkin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_olive.zip -O ./zip/original_olive.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_cyan.zip -O ./zip/original_cyan.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_brown.zip -O ./zip/original_brown.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_bluegreen_darker.zip -O ./zip/original_bluegreen_darker.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_blue.zip -O ./zip/original_blue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/original_black.zip -O ./zip/original_black.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_asus.zip -O ./zip/nadi_asus.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_buffalo.zip -O ./zip/nadi_buffalo.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_dlink.zip -O ./zip/nadi_dlink.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_linksys.zip -O ./zip/nadi_linksys.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/nadi_netgear.zip -O ./zip/nadi_netgear.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/linksysred.zip -O ./zip/linksysred.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/asusred.zip -O ./zip/asusred.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/asus.zip -O ./zip/asus.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/rs232.zip -O ./zip/rs232.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_aqua.zip -O ./zip/basic_aqua.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_azure.zip -O ./zip/basic_azure.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_banana.zip -O ./zip/basic_banana.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_black.zip -O ./zip/basic_black.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_blue.zip -O ./zip/basic_blue.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_cherry.zip -O ./zip/basic_cherry.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_chocolate.zip -O ./zip/basic_chocolate.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_earth.zip -O ./zip/basic_earth.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_eggplant.zip -O ./zip/basic_eggplant.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_emerald.zip -O ./zip/basic_emerald.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_gold.zip -O ./zip/basic_gold.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_green.zip -O ./zip/basic_green.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_grey.zip -O ./zip/basic_grey.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_gunmetal.zip -O ./zip/basic_gunmetal.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_hotpink.zip -O ./zip/basic_hotpink.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_lavender.zip -O ./zip/basic_lavender.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_lightpurple.zip -O ./zip/basic_lightpurple.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_lime.zip -O ./zip/basic_lime.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_magenta.zip -O ./zip/basic_magenta.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_melon.zip -O ./zip/basic_melon.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_mint.zip -O ./zip/basic_mint.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_mustard.zip -O ./zip/basic_mustard.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_navy.zip -O ./zip/basic_navy.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_olive.zip -O ./zip/basic_olive.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_orange.zip -O ./zip/basic_orange.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_peach.zip -O ./zip/basic_peach.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_petrol.zip -O ./zip/basic_petrol.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_pink.zip -O ./zip/basic_pink.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_pumpkin.zip -O ./zip/basic_pumpkin.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_purple.zip -O ./zip/basic_purple.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_red.zip -O ./zip/basic_red.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_rosybrown.zip -O ./zip/basic_rosybrown.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_salmon.zip -O ./zip/basic_salmon.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_sand.zip -O ./zip/basic_sand.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_smoke.zip -O ./zip/basic_smoke.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_strawberry.zip -O ./zip/basic_strawberry.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_turquise.zip -O ./zip/basic_turquise.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_wheat.zip -O ./zip/basic_wheat.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_white.zip -O ./zip/basic_white.zip
wget http://www.tomatothemebase.eu/wp-content/uploads/basic_yellow.zip -O ./zip/basic_yellow.zip
